site_name: Reach RS docs
theme_dir: docstheme
site_favicon: favicon.ico
repo_url: https://github.com/emlid/reachrs-docs
extra:
  palette:
    primary: 'light blue'
    accent: 'light blue'
  logo: 'rreachview/img/logo.png'
  social:
    - type: 'github'
      link: 'https://github.com/emlid'
    - type: 'twitter'
      link: 'https://twitter.com/emlidtech'
    - type: 'facebook'
      link: 'https://facebook.com/emlidtech' 
  google_analytics:
    - 'UA-49508097-6'
    - 'auto'
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

pages:
- Introduction: index.md
- Power supply: reachrs-power-supply.md
- Antenna placement: reachrs-unit-placement.md
- ReachView app:
  - Introduction: reachview/reachview.md
  - Settings: reachview/reachview-settings.md
  - Status: reachview/reachview-status.md
  - 'RTK settings': 'reachview/reachview-rtk-settings.md'
  - 'Correction input': 'reachview/reachview-correction-input.md'
  - 'Position output': 'reachview/reachview-position-output.md'
  - 'Base mode': 'reachview/reachview-base-mode.md'
  - 'Logging': 'reachview/reachview-logging.md'
  - 'Camera control': 'reachview/reachview-camera-control.md'
  - 'Wi-fi/Bluetooth': 'reachview/reachview-connectivity.md'
  - 'Firmware reflashing': 'reachview/reachview-firmware-reflashing.md'
  - 'LED status': 'reachview/reachview-led-status.md'
  - 'Changelogs': 'reachview/reachview-changelogs.md'
- Specification: reachrs-specs.md
- Tutorials:
  - How RTK works: reachview/rtk-introduction.md
  - Quickstart: reachrs-quickstart.md
  - GPS post-processing: reachview/gps-post-processing.md
  - 'Bluetooth output and Android mock location': 'reachview/reachview-lefebure.md'
